name: low-uv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools>=78.1.1
  - pip>=25.0
  - setuptools-scm
  - uv
  - ruff
  - pre-commit
  - makefun
  # common
  - cython
  - loguru
  - joblib
  - tqdm
  - tzdata
  - pyyaml
  # data analysis
  - numpy
  - xarray
  - pandas
  - h5py
  - hdf5plugin
  - jax
  # astro
  - astropy
  - healpy
  - pyshtools
  - python-casacore==3.5.2
  - casacore
  - sgp4
  # plotting
  - jupyterlab
  - matplotlib
  - ipympl
  - ipywidgets
  - llvm-openmp
  # Pytest
  - pytest
  - pytest-cov
  - pytest-mpl
  - colored
  # Docs
  - sphinx
  - sphinx-autodoc-typehints
  - myst-nb
prefix: /Users/daniel.price/local/mamba/envs/low-uv
