# UVX configuration file
history: Created with scripts/uv-config-from-mccs-yaml at 2025-08-31 07:16:47.986
instrument: s8-1
telescope_name: s8-1
telescope_ECEF_X: -2561233.117894838
telescope_ECEF_Y: 5085888.89542364
telescope_ECEF_Z: -2864153.9782395344
channel_spacing: 781250.0           # Channel spacing in Hz
channel_width: 925926.0             # 781250 Hz * 32/27 oversampling gives channel width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
receptor_angle: 251.3            # clockwise rotation angle in degrees away from N-E
conjugate_hdf5: true               # Apply complex conjugation to HDF5 data when loading
transpose_hdf5: true               # Transpose cross-pol terms when loading HDF5 data
vis_units: uncalib
