# UVX configuration file
history: Created with scripts/uv-config-from-mccs-yaml at 2025-08-31 07:16:47.680
instrument: s10-4
telescope_name: s10-4
telescope_ECEF_X: -2557862.9426917788
telescope_ECEF_Y: 5087168.107557088
telescope_ECEF_Z: -2864878.8271829486
channel_spacing: 781250.0           # Channel spacing in Hz
channel_width: 925926.0             # 781250 Hz * 32/27 oversampling gives channel width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
receptor_angle: 315.8            # clockwise rotation angle in degrees away from N-E
conjugate_hdf5: true               # Apply complex conjugation to HDF5 data when loading
transpose_hdf5: true               # Transpose cross-pol terms when loading HDF5 data
vis_units: uncalib
