name: Docker Image CI

on:
  push:
    branches: ["master", "master-dev"]
  pull_request:
    branches: ["master", "master-dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file ops/docker/Dockerfile --tag dsa110-contimg:$(date +%s)
